research_task:
  description: >
    Conduct a research task on a given topic and gather relevant information.
  expected_output: >
    A detailed summary with key findings.
  human_input: false
  max_iterations: 3

execution_task:
  description: >
    Execute a specific task, such as implementing a solution.
  expected_output: >
    A step-by-step execution result.
  human_input: false
  max_iterations: 3

analysis_task:
  description: >
    Perform analysis on a given data set or performance metrics.
  expected_output: >
    A detailed report with insights and optimizations.
  human_input: false
  max_iterations: 3
